# Generated by Django 6.1 on 2026-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_movimiento_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo (kg)'), ('lb', 'Libra (lb)'), ('g', 'Gramo (g)'), ('und', 'Unidad (und)'), ('L', 'Litro (L)'), ('ml', 'Mililitro (ml)')], max_length=10),
        ),
    ]
