# Generated by Django 6.1 on 2026-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
