# Generated by Django 6.1 on 2026-08-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_movimiento_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto'),
        ),
    ]
